Adding the folder for 2019 Bling code
Spartronics4915/Bling pull request #8
Opened 2019-01-20 21:45 UTC by thehappycamden

Nothing to add right now.

2019-01-20 22:47 UTC, binnur commented
@thehappycamden why is it unnamed? '2019-Unnamed-NeoPixel/2019-Unnamed-NeoPixel.cbp'

2019-01-21 03:19 UTC, pietroglyph commented
I think it’s unnamed because the past naming convention was “year-robotname-NeoPixel”, and we don’t know the robot name yet. We may want to change the convention and all of the folders so that it doesn’t include robot names.

2019-02-02 08:09 UTC, pietroglyph reviewed
I made some comments, and I think you have some good work here, but there are a couple of things you need to address generally:

- Please format all of your files before committing. This is a built-in feature of the Arduino IDE.
- Please remove obsolete code before committing. It is difficult to tell what you're using and what you're not using.
- Try to use clearer variable names. Avoid single letters. I (personally) prefer to err on the side of verbosity and I like to use a full word whenever reasonable (`pattern` instead of `pat`, `display` instead of `disp`).
- **It's clear that you haven't pushed in a while. Please, please, please push your code at the end of every meeting.** For everyone's sanity, your PR should be up to date at all times.

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/2019-Unnamed-NeoPixel.ino
> +const int decStripPin = 11;
Are there possibly better names for these? Maybe `displayStripPin`, `displayStripControlPins` (I don't know about `decStripPin`; that's currently unused, should it be removed?)

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/Bling.cbp
> +<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
If you're currently using the Arduino IDE you might want to remove these Code::Blocks files.

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/Bling.layout
> +<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
Remove me?

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/DisplayBase.ino
> +#define NUM_ptrn 4
Refactor to `NUM_PATTERN` for clarity and to match the naming convention.

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/DisplayBase.ino
> +Adafruit_NeoPixel pixels(12, 4, NEO_GRB + NEO_KHZ800);
You should probably use `NUM_PIXELS` and `NUM_PATTERN` here instead of `12, 4`.

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/DisplayBase.ino
> +    if (++id >= 5)
This could be `if (++id >= sizeof(patterns) / sizeof(patterns[0])) { ... }`

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/convert.py
> +with open("main.cpp") as f:
Why is this file here?

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/main.cpp
> +// Mostly copied from 2017 code.
This is a duplicate of the `2019-Unamed-NeoPixel.ino`. You might remove this.

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/pat.h
> +    virtual void loop(int loopCounter) {};
You should probably make these pure virtual. E.g.:

```c++
virtual void loop(int loopCounter) = 0;
```

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/DisplayBase.ino
> +};
This is an interesting style of encapsulating these patterns... I was going to suggest a more object-oriented style, but I see that you used that in `pat.h`. Does that make this file obsolete?

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/patAlternate.h
> +    CRGB m_c1, m_c2;
Maybe `m_colorOne` and `m_colorTwo`?

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/pat.h
> +class pat
Maybe rename this to `Pattern`.

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/patAlternate.h
> +class patAlternate : public pat
Maybe `AlternatingPattern`.

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/patFill.h
> +class patFill : public pat
Maybe `FillPattern`?

2019-02-02 08:09 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/2019-Unnamed-NeoPixel.ino
> +    Serial.println("Wazza?");
Perhaps something more informative (e.g. `Serial.println("Spartronics 2019 Bling starting..."`).

2019-02-03 18:33 UTC, pietroglyph requested changes
This looks pretty good, I just have a couple of nitpicks you should address.

2019-02-03 18:33 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/generateAnimation.py
> +from PIL import Image
Why is this here?

2019-02-03 18:33 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/2019-Unnamed-NeoPixel.ino
> +void forwards()
The patterns could use better names (e.g. this looks like it's `disabled`). The patterns _other_ than `forwards*/backwards*` have fine names.

2019-02-03 18:33 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/2019-Unnamed-NeoPixel.ino
> +  }else if (newCommand == '\0')
Format this file correctly.

2019-02-03 18:33 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/2019-Unnamed-NeoPixel.ino
> +  Serial.println("Hello, -- HELP! I'M TRAPPED IN AN ARDUINO FACTORY!! -- LEDs!");
I approve of this :)

2019-02-03 18:33 UTC, pietroglyph commented on 2019-Unnamed-NeoPixel/2019-Unnamed-NeoPixel.ino
> +    Serial.println("");
Maybe print invalid?

2019-02-16 06:41 UTC, pietroglyph approved these changes

2019-02-16 06:41 UTC, pietroglyph commented
Looks good!

2019-02-16 06:41 UTC, merged